-- Moderation gate — INSTALLED AND INERT. One statement away from enforcing.
--
-- The schema, the trigger function and the trigger are already applied to the
-- live project (migration: install_artwork_moderation_gate_inert). The secret
-- row exists but is EMPTY, and an empty secret makes the trigger return
-- immediately, so behaviour today is exactly what it was before.
--
-- ============================================================ what it closes
-- The insert policy on artworks is:
--
--   artworks_insert_own  INSERT  CHECK (auth.uid() = user_id AND current_merit() >= 80)
--
-- There is no constraint on `status`. So any signed-in account with merit >= 80
-- can POST straight to PostgREST with status='approved' and never call
-- /api/moderate-upload. The client writes mod_token, but until this gate is
-- live nothing verifies it. The AI check is a UX gate, not a security one.
--
-- ============================================================ how it works
-- /api/moderate-upload mints a single-use ticket after an image passes:
--
--   msg    = "<uid>.<exp>.<jti>"
--   sig    = HMAC-SHA256(msg, MOD_SIGNING_SECRET), lowercase hex
--   token  = "<exp>.<jti>.<sig>"            (valid 10 minutes)
--
-- The trigger recomputes that HMAC with the secret stored below and compares.
-- Verified empirically, not just by reading: a token minted with Node's crypto
-- and the signature recomputed by Postgres agree byte for byte.
--
-- Insert outcomes, all confirmed against a non-dev account:
--
--   no token          -> status forced to 'pending'   <-- the bypass, closed
--   valid ticket      -> stays 'approved'
--   ticket replayed   -> 'pending'  (jti primary key)
--   expired ticket    -> 'pending'
--   tampered sig      -> 'pending'
--   malformed token   -> 'pending'
--   status='pending'  -> untouched, needs no ticket
--
-- Paths that stay trusted, by design:
--   auth.uid() IS NULL   server / service-role context. This is what lets the
--                        pg_cron job publish_due_scheduled_uploads keep
--                        publishing scheduled artwork every 5 minutes.
--   public.is_dev()      staff accounts skip the ticket.
--
-- ============================================================ ACTIVATION
-- ORDER MATTERS. Setting the secret here first would mean the Worker mints no
-- ticket, every insert fails the check, and every upload silently lands in
-- 'pending'. So:
--
--   1. Cloudflare Pages -> Settings -> Environment variables -> Production
--      add  MOD_SIGNING_SECRET  = <the secret>
--   2. Redeploy the site, so the Worker picks the variable up.
--   3. Upload one artwork through the site and confirm it publishes normally.
--   4. Only then run the statement below, with the SAME value.
--
-- update private.mod_config
--    set secret = '<the same secret as MOD_SIGNING_SECRET>'
--  where id = true;
--
-- The secret is deliberately not written in this file. It is a credential; it
-- belongs in the Cloudflare dashboard and the database, not in git.
--
-- ============================================================ verify
-- select case when secret = '' then 'inert' else 'enforcing' end
--   from private.mod_config where id = true;
--
-- select tgname from pg_trigger
--  where tgrelid = 'public.artworks'::regclass and not tgisinternal;
--
-- After a few real uploads, tickets should be accumulating:
-- select count(*) from private.used_mod_tokens;
--
-- ============================================================ roll back
-- Make it inert again without dropping anything:
--   update private.mod_config set secret = '' where id = true;
--
-- Remove it entirely:
--   drop trigger if exists trg_artwork_mod_gate on public.artworks;
--   drop function if exists public.dz_artwork_mod_gate();
--   drop table if exists private.used_mod_tokens;
--   drop table if exists private.mod_config;
--
-- ============================================================ still open
-- This gate covers public.artworks only. Resources, marketplace items, blog
-- posts and comics are inserted from js/sections.js against their own tables
-- and have no equivalent ticket check. /api/moderate-upload already has a
-- RESOURCE_PROMPT path, so the moderation exists; the enforcement does not.
--
-- Text moderation is also client-side only. js/badwords.js wraps
-- supabase.createClient and scrubs insert/upsert/update payloads for artworks,
-- comments, DMs, profiles and more. It is a display filter: the same direct
-- PostgREST call that this gate now blocks would also skip the scrubbing.
